Add fb-scene-sample project
GodotVR/godot_openxr_vendors pull request #173
Opened 2024-06-21 17:27 UTC by devloglogan

Adds a sample project showcasing the FB extensions for scene and spatial anchors, and removes the same examples from the demo project.

I've also added a `.gdignore` file in the `samples/builds` directory, as David pointed out to me that exporting the file doesn't work unless that directory exists beforehand.

2024-06-24 16:31 UTC, m4gr3d requested changes

2024-06-26 13:22 UTC, devloglogan commented on samples/fb-scene-sample/main.gd
> +		vp.use_xr = true
Even though this puts a couple things in the sample that end up unused, I think it makes sense to do this. In my latest push I've modified `main.gd` to follow the better start script template verbatim (comments and all). If we decide this is good, I'll update the rest of the samples accordingly.

2024-06-26 16:07 UTC, m4gr3d commented on samples/fb-scene-sample/main.gd
> +		vp.use_xr = true
> Edit: perhaps adding a comment at the top of the scripts indicating that the better start script doc was used as a starting template would be worthwhile?

Yeah, good idea!

2024-06-26 16:08 UTC, m4gr3d approved these changes
Looks good!

2024-06-28 12:17 UTC, devloglogan commented on samples/fb-scene-sample/main.gd
> +		vp.use_xr = true
I added a comment with a note / link to the doc, once the doc exists in stable I'll update it to that.

2024-06-28 19:30 UTC, merged